In [3]:
#Trevor Taylor

#First we must download the iris flower data

from sklearn.datasets import load_iris
dataset = load_iris()

#We must create a data set and target set to see how well we can predicted a target based on data

X = dataset.data
Y = dataset.target
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

In [4]:
#It is much easier to work with 1 and 0s on a computer instead of normal values
#To do this we take each of the columns and find the adverage of each
#We assign a 1 to values over the adverage and a 0 to those bellow

#To do this I split the data into 4 seperate arrays since I was having trouble doing this otherwise

import numpy as np
X_d0 = np.array( X[:,0] > X[:,0].mean(), dtype = 'int')
X_d1 = np.array( X[:,1] > X[:,1].mean(), dtype = 'int')
X_d2 = np.array( X[:,2] > X[:,2].mean(), dtype = 'int')
X_d3 = np.array( X[:,3] > X[:,3].mean(), dtype = 'int')

#X_d = np.array( X > X.mean(), dtype='int')

In [5]:
#Now since we have four arrays and we want one we must join them together
#In order to do this they must all have the same shape so we use resape to change them from a (150,) to (150,1)

X_d0r = X_d0.reshape(150,1)
X_d1r = X_d1.reshape(150,1)
X_d2r = X_d2.reshape(150,1)
X_d3r = X_d3.reshape(150,1)

In [6]:
from collections import OrderedDict
import pandas as pd

#Using pandas to look at the data

Iris_data_d = OrderedDict({'Sepal Length ': X_d0r[:,0],
             'Sepal Width': X_d1r[:,0],
             'Petal Length': X_d2r[:,0],
             'Petal Width': X_d3r[:,0],
             'Label': Y})

df = pd.DataFrame(Iris_data_d)
df

     Sepal Length   Sepal Width  Petal Length  Petal Width  Label
0                0            1             0            0      0
1                0            0             0            0      0
2                0            1             0            0      0
3                0            1             0            0      0
4                0            1             0            0      0
5                0            1             0            0      0
6                0            1             0            0      0
7                0            1             0            0      0
8                0            0             0            0      0
9                0            1             0            0      0
10               0            1             0            0      0
11               0            1             0            0      0
12               0            0             0            0      0
13               0            0             0            0      0
14               0            1             0            0      0
15               0            1             0            0      0
16               0            1             0            0      0
17               0            1             0            0      0
18               0            1             0            0      0
19               0            1             0            0      0
20               0            1             0            0      0
21               0            1             0            0      0
22               0            1             0            0      0
23               0            1             0            0      0
24               0            1             0            0      0
25               0            0             0            0      0
26               0            1             0            0      0
27               0            1             0            0      0
28               0            1             0            0      0
29               0            1             0            0      0
..             ...          ...           ...          ...    ...
120              1            1             1            1      2
121              0            0             1            1      2
122              1            0             1            1      2
123              1            0             1            1      2
124              1            1             1            1      2
125              1            1             1            1      2
126              1            0             1            1      2
127              1            0             1            1      2
128              1            0             1            1      2
129              1            0             1            1      2
130              1            0             1            1      2
131              1            1             1            1      2
132              1            0             1            1      2
133              1            0             1            1      2
134              1            0             1            1      2
135              1            0             1            1      2
136              1            1             1            1      2
137              1            1             1            1      2
138              1            0             1            1      2
139              1            1             1            1      2
140              1            1             1            1      2
141              1            1             1            1      2
142              0            0             1            1      2
143              1            1             1            1      2
144              1            1             1            1      2
145              1            0             1            1      2
146              1            0             1            1      2
147              1            0             1            1      2
148              1            1             1            1      2
149              1            0             1            1      2

[150 rows x 5 columns]

In [7]:
#Also we must join the target set to the other set and to do so we need it to change its dimentions as well

Y_d = Y.reshape(150,1)

In [8]:
#Using np.hstack we can rejoin the arrays to form one full array

Z_d = np.hstack([X_d0r,X_d1r,X_d2r,X_d3r,Y_d])

In [9]:
#To get the one rule algorythm we must see which one of our four variables correlates to the flower type the most
#What I did here was test how often a variable was over its average and how often that correlated to a certain flower type
#i = 0 means Speal length
#i = 1 means Speal width
#i = 2 means Petal length
#i = 3 means Petal width
#j = 0 means Setosa
#j = 1 means Versicolor
#j = 2 means Virginica

values = []
for i in range(4):
    for j in range(3):
        selection = np.logical_and(Z_d[:,i]>.9,Z_d[:,4] == j)
        values.append(('i', i, 'j', j,'value', len(Z_d[selection]), 'percentage is', ((len(Z_d[selection])/len(Z_d[:,i]))*100)))

In [10]:
values

[('i', 0, 'j', 0, 'value', 0, 'percentage is', 0.0),
 ('i', 0, 'j', 1, 'value', 26, 'percentage is', 17.333333333333336),
 ('i', 0, 'j', 2, 'value', 44, 'percentage is', 29.333333333333332),
 ('i', 1, 'j', 0, 'value', 42, 'percentage is', 28.000000000000004),
 ('i', 1, 'j', 1, 'value', 8, 'percentage is', 5.333333333333334),
 ('i', 1, 'j', 2, 'value', 17, 'percentage is', 11.333333333333332),
 ('i', 2, 'j', 0, 'value', 0, 'percentage is', 0.0),
 ('i', 2, 'j', 1, 'value', 43, 'percentage is', 28.666666666666668),
 ('i', 2, 'j', 2, 'value', 50, 'percentage is', 33.33333333333333),
 ('i', 3, 'j', 0, 'value', 0, 'percentage is', 0.0),
 ('i', 3, 'j', 1, 'value', 40, 'percentage is', 26.666666666666668),
 ('i', 3, 'j', 2, 'value', 50, 'percentage is', 33.33333333333333)]

In [11]:
#From this we can see that 
#The best one rule for Setosa is to look at its Sepal Width
#The best one rule for Versicolor is to look at either its Petal length or its Petal width since they are so close
#The best one rule for Viginica is to look at its Petal length and Petal width since they are the same